### ISSUE TITLE
How to get all tag of series ?

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#11]
Hi @knopkem !
I found in the file src/app.js. You filter the tag to get meda data of series. It is ok.
![TagFilter](https://user-images.githubusercontent.com/20145650/93966462-f96bdb00-fd8e-11ea-878a-35eb2fa42512.PNG)

But, if I want to get all tag of series, what should I do ?
Can you point to me the way to do it ?
Thank you so much !

**Comment by knopkem** [comment]
Hi,
in fact, what you found is not filtering but adding some default tags to each query (required for the OHIF viewer which is not correctly using dicomweb and should request those). 
The normal procedure with dicomweb would be that the client always includes the attributes he is interested in with each query. This is done via query parameters in the form of .../rs/studies/:studyInstanceUid/?includefield=00200020&includefield=00100010 etc. or using the normalized attribute names (not recommended, but supported): ...?includefield=PatientName
See http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.3.1

So this is what you can do (if you look into utils.js doFind method you can see that I filter includefield queries and add those to the request array.
In dicomweb the following should normally also be supported (but currently isn't in with the proxy): query?includefield=all
This should return all supported attributes at that level, however since this is a proxy it doesn't know which attributes are actually supported on the PACS. The list of required attributes is very limited: https://www.medicalconnections.co.uk/kb/Query-Parameters/
But I will add the 'all' parameter nonetheless requesting the most common attributes from the PACS (it doesn't hurt to request tags which are not supported). Cheers.

**Comment by knopkem** [comment]
Btw. I recommend reading Part 18 of the DICOM standard (about dicomweb). Personally I prefer the version from 2018 which is much easier to understand than the current version (I don't know why they messed this up so much): http://dicom.nema.org/medical/dicom/2018d/output/html/part18.html

**Comment by dinhnam2901** [comment]
I see it. Thank for your answer!
