### ISSUE TITLE
Error find studies in Conquest

### ISSUE THREAD

**Issue by omechris** [knopkem/dicomweb-proxy#14]
Hi,
Using dicomweb-proxy with Conquest 1.5.0 gives a find error.
Log dicomweb-proxy:
![proxylog](https://user-images.githubusercontent.com/23418848/104169340-b302c080-53ff-11eb-998a-cddb82c5c378.png)
Log Conquest:
![conquestlog](https://user-images.githubusercontent.com/23418848/104169572-11c83a00-5400-11eb-9a85-52ee66ab8ef1.png)

C-Echo goes well.
Any Clues?

Chris

**Comment by knopkem** [comment]
Hmm, looks like the problem rather comes from CONQUEST having problems with the dataset. (When trying to parse the data to create the response).
Could you try to perform a similar c-find with any other tool/workstation?

**Comment by omechris** [comment]
I tried findscu (DCMTK tools) and this works fine.

**Comment by knopkem** [comment]
I just tested with latest conquest and the default dataset that comes with it. There are no issues. I still suspect this is dataset specific which is why I would need a sample dicom to reproduce. Any chance you could (anonymize) and upload?

![conquest](https://user-images.githubusercontent.com/994526/104198253-4cdd6400-5426-11eb-84cd-d682311dad56.PNG)

**Comment by omechris** [comment]
You're right.
With Conquest running on a Windows box everything runs OK.
Must be a problem running Conquest on a Linux box.
I'll investigate.
Thank you for your support.

Chris
