### ISSUE TITLE
An error occurs when run: npm install dicomweb-proxy

### ISSUE THREAD

**Issue by lam0620** [knopkem/dicomweb-proxy#2]
Hi

I got an error when run: npm install dicomweb-proxy.

What should I do?

![image](https://user-images.githubusercontent.com/12405565/79530060-7e442180-8098-11ea-9c01-5524d83e24f4.png)

ENV:
Windows 10 Pro
Node 10.15.3
NPM 6.4.1

Thank you!

**Comment by knopkem** [comment]
Hi,
it means that the precompiled dependency dicom-dimse-native was not found for your environment and it than tries to compile it from source but fails as you don't have the tools installed for it. Don't worry normally compilation from source is not needed.
The reason it didn't find it in the first place is, that I only uploaded prebuild packages for node version 12.x.x yet, so all you need to do is update your node version to latest LTS (12.16.2) or more recent versions. If you really can't do that, I can walk you through the process of self compilation which isn't hard, but you would need at least node version v10.16.0 for it to work.

**Comment by lam0620** [comment]
Thank you so much @knopkem!
 I'll upgrade  nodejs to 12.16.2 and try again

**Comment by lam0620** [comment]
Hi @knopkem 

I can run dicomweb-proxy with nodejs 12.16.2.
When I access localhost:5000, a studylist is dispalyed. Studylist search also works too.
However, an error occurs when a study is clicked to go to viewer.

I use ClearCanvas PACS Server.
I just modify to config PACS as below (./config/default.js)
```
// our target PACS
config.target = {
  aet: "VTH",
  ip: "192.168.201.41",
  port: "106"
};
```
I'd appreciated if you could help me

![image](https://user-images.githubusercontent.com/12405565/79826955-43f3c080-83c7-11ea-92ca-638db2844230.png)

![image](https://user-images.githubusercontent.com/12405565/79826812-e3648380-83c6-11ea-9ee0-0af6f03a246a.png)

**Comment by knopkem** [comment]
Ok, I see, one of the problems I need to fix is that the sometimes errors returned from the native plugin are not properly escaped which doesn't help to trace the actual issue. Will have a look.

**Comment by knopkem** [comment]
Can you try again with the latest version of dicom-proxy (master). Make sure to also npm install afterwards to get the latest dimse-native plugin. I updated the native plugin to always send valid json so it should not throw when errors occur.
I tried with clearcanvas (localhost only) and had to use C-Move, C-Get seems not supported. Also make sure to register the PROXY AET name otherwise Clearcanvas doesn't know where to "move" the data to. It did work for me. If the server is on another host, make sure to update firewalls accordingly. Let me know if it worked or what the error was.

**Comment by lam0620** [comment]
Hi @knopkem 

I'm sorry, How can I register the PROXY AET name?

**Comment by knopkem** [comment]
I meant in ClearCanvas you need to add the proxy as a remote server using the AET as in your default.js file (e.g. DICOMWEB_PROXY) see https://documentation.clearcanvas.ca/Documentation/UsersGuide/Workstation/2_0_SP1/

**Comment by lam0620** [comment]
Thank you so much @knopkem 
It works well!

However, I recognize that image viewer performance is slow because DICOM images must be downloaded to dicomweb-proxy first and then display.
If I switch to view DICOM from wadouri to WADO standard (that CC support), it seem the load performance is better (image streaming, no download need).

More question:
Dicomweb-proxy comes with preinstall OHIF Viewer.
1. If I rebuild latest OHIF viewer, how can include the OHIF viewer  into dicomweb-proxy?
2. If I want to run Ohif viewer separately, how can I config to call dicoweb-proxy?

Cheers,
lam0620

**Comment by knopkem** [comment]
Good that it works @lam0620 

It's normal that the proxy will be slower than a native dicomweb connection as it always has to reroute the data. I recommend to install the proxy on the same host as the PACS for faster transfer.
The idea of the proxy is to use it with legacy PACS that doesn't speak dicomweb.
There is still room for performance improvement though (e.g. showing the first image while still downloading images, this will come over time.

Regarding your questions:
1. There are multiple ways to do this. You can generate a bundle and replace the files in /public/viewer. In OHIF source folder use the command  'npm run build:package'. The files are then ready in: 'ohif/platform/viewer/dist'. This is what I would recommend. 
Alternatively you can generate the 'normal' OHIF build (lots of small files) by building using 'npm run build:viewer' and host it using any web server (e.g. ngnix). You will need to update the default.js config file in 'ohif/platform/viewer/public/config' to point to the proxy, however there is a unresolved (and closed) bug: https://github.com/OHIF/Viewers/issues/1494 which makes this a bit cumbersome
However the biggest issue currently and this is why I still use V.3.7.7 is https://github.com/OHIF/Viewers/issues/1638 so currently updating is not possible. I started a branch 'deepMeta' which works around this issue (almost done) but it's not nice and I would rather have the issue fixed in OHIF. Hopefully, I can do this at one point.

**Comment by knopkem** [comment]
2. Was already answered before. For the current v3.7.7 version you can just host the public folder in this repo anywhere and update app-config.js to point to the proxy (note that issue #1494 applies). I might add a wiki for that in fact. Good luck

**Comment by lam0620** [comment]
I understood the situation.

Close and Thank you for your support!
