### ISSUE TITLE
WADO Calls kills the server

### ISSUE THREAD

**Issue by ferranalma3d** [knopkem/dicomweb-proxy#22]
Hi Again,

No is working but with ohif and dicom4chee all the studies give the same error and server crashes

I've checked de log but there's the same info

14:41:36.725 INFO  storeddata\1.2.826.0.1.3680043.2.403.53.1150416105135925.1.345051961227
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dicomweb-proxy@1.0.16 start: `node src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dicomweb-proxy@1.0.16 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ferra\AppData\Roaming\npm-cache\_logs\2021-03-26T13_41_36_753Z-debug.log

Thx a lot again!

![image](https://user-images.githubusercontent.com/69808749/112640518-b2e06180-8e41-11eb-842e-bd1005c54ffb.png)
![image](https://user-images.githubusercontent.com/69808749/112640568-bd026000-8e41-11eb-9a44-08dab9bdffe8.png)
![image](https://user-images.githubusercontent.com/69808749/112640623-ca1f4f00-8e41-11eb-9e1d-f725450aadd2.png)

**Comment by knopkem** [comment]
Hi, 
did you modify the default value in the default.js config for storagePath? It looks to me that it wants to store the data using an invalid path.
Do you use C-Get or C-Move (config.useCget). Its recommended to use C-GET with DCM4CHEE.
I tested both and it was working for me. Maybe post your default.js config.

**Comment by knopkem** [comment]
Hi, I could reproduce the crash and applied some code changes to fix it.
The reason was an unhandled exception due to a failed c-move operation. This can happen e.g.
* when dcm4chee is misconfigured and does not know the destination (DICOMWEB_PROXY)
* when dcm4chee is misconfigured and uses a wrong port for the destination (that actually points to a valid C-STORE server)
Especially case 2 is tricky as the proxy thinks that the data should be there as the move request was actually successful. So pull the latest changes, check your dcm4chee settings and try again. Otherwise post the logs here. Cheers

**Comment by ferranalma3d** [comment]
Hi!!

Thanks a lot! :)
