### ISSUE TITLE
Error Getting very small images 

### ISSUE THREAD

**Issue by goddymugo** [knopkem/dicomweb-proxy#40]
Hi, am using dicomweb-proxy connected to conquest server.
When images load, they are to noisy with magnification of over 400% and no patient information is displayed on viewer.
Set Conquest to forward all images to KPacs and the images in KPacs look good and load with normal magnification of about 0.8 and shows patient information.
![image](https://user-images.githubusercontent.com/29998260/128475659-75bd99bb-77d4-4d15-bb12-45519ca618d8.png)
![Capture](https://user-images.githubusercontent.com/29998260/128475770-b642d391-769f-46e9-a0cb-a28e6fdcafe1.JPG)

**Comment by knopkem** [comment]
Hi,
the project I maintain here is only about a dicomweb to dimse proxy. It should be independent of the dicomweb viewer used. While it bundles the [OHIF viewer](https://github.com/OHIF/Viewers) as an example, I do not maintain it. 
However, it could also have been caused by the proxy when compressing the images. To exclude this potential problem, please modify the default.js file: config.transferSyntax = '1.2.840.10008.1.2.4.80';
This should disable any compression, decompression (which normally is lossless and should not cause any degradation) 
Otherwise please contact the guys at OHIF for any viewer related issues. Cheers

**Comment by goddymugo** [comment]
Dear Knopkem,

Thanks for your timely respose.


Kind regard,
Godfred Mugoma.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
