### ISSUE TITLE
Upgrade of OHIF Viewer or features

### ISSUE THREAD

**Issue by hammoo** [knopkem/dicomweb-proxy#41]
Hi 

First of all thanks for a great software. Can you guide me how can we upgrade the current version of OHIF Viewer to the latest version (I am not an IT Personnel) or add additional features in the current like MIP, MPR etc.

**Comment by knopkem** [comment]
Hi,

the process of updating OHIF is pretty simple, here is what you need to do:

## You will need:
* a recent Node and yarn version
* python2 installed (needed for node-sass dependency)

## Build new version
* checkout the OHIF viewer repo
* yarn install
* yarn build

## Update built-in viewer 
* Make a copy of public/app-config.js
* copy content of {Viewers}\platform\viewer\dist into ./public folder of dicomweb-proxy.
* override app-config.js file in public folder with the copy you made before

However, I have already done this now. So latest version is 4.9.21.
Regarding MPR: normally even if you update the verison, this would not be enabled, as the OHIF viewer requires WADO-RS (an advanced route of DICOMWEB) for this to work. The previous version of dicomweb-proxy provided only WADO-URI which is the most straightforward conversion between legacy dicom dimse networking and dicomweb. In the latest version I switched to WADO-RS and MPR should now work, however it requires a fast connection between the proxy and the PACS as it needs to fetch the whole series before opening the viewer (different to WADO-URI where the viewer would not have to wait). 

Let me know if it works for you.

**Comment by wx0322** [comment]
hi now, the wado-rs features has released?

**Comment by knopkem** [comment]
Yes wado-rs is working and OHIF with MPR should be active by default, though no MIP/VRT (as far as I know OHIF viewer does not yet support it)

**Comment by wx0322** [comment]
thanks.

**Comment by andyle2k** [comment]
Hi @knopkem 

Did you switch from WADO-URI to WADO-RS because of the metadata issue you found (https://github.com/OHIF/Viewers/issues/1638)?

I want to use the latest OHIF but it's impossible with WADO-URI because it's lacking their required metadata.

I'm in a very similar boat. I too am working on a proxy type app for my PACS but using dotnet. You commented on my other post regarding how to identify CMOVE stores on the SCP for the use of the proxy (safely deleting them after responding to the proxy's requests). 

I'm dreading having to download the entire study before launching the viewer but that might be the only option. 

Also, I tried reaching out but I don't have a LinkedIn - maybe you can contact me if you don't mind: andyle2k (at) gmail (dot) com

Thanks.
