### ISSUE TITLE
Does Dicom proxy support for the v3-stable version of OHIF

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#65]
Dear @knopkem 

I have one question for you. 

Does Dicom proxy support for the v3-stable version of OHIF at link https://github.com/ohif/viewers/tree/v3-stable ?
Looking forward to your response.

I trying to use it, and the error was occur.
![141086238-259e1fb1-e851-4634-919c-9743cc82519f](https://user-images.githubusercontent.com/20145650/150243975-f1fa8467-830d-498f-a7cd-48d156a81772.png)

Thank you very much!

**Comment by knopkem** [comment]
Hi,
I remember that I had this issue before when testing with v3. This time I copied and updated the app-config.js instead of reusing the old one and I guess this was the issue. It does work now. Please checkout branch ohif-v3 to use it. However as long as it is not in master I will not updated the master branch. (Also I noticed that MPR is not available).
Cheers.

**Comment by dinhnam2901** [comment]
I understand, it will try it.
Thank you for your support!
