### ISSUE TITLE
I changed the query level in the configuration, but the list still can't show the name.

### ISSUE THREAD

**Issue by fightroad** [knopkem/dicomweb-proxy#75]
![image](https://user-images.githubusercontent.com/39027157/160219966-9d36c135-ddb8-45da-a216-dffaa54aab62.jpeg)

**Comment by knopkem** [comment]
Hi,
changing the query level will not help here, best to let it at "series". 
I believe that the issue comes from characterset conversion issues. This can have a multiple causes, so to find out more could you please:
- tell me the name of the PACS that you query
- turn on verboseLogging in dicomweb-proxy
- either send parts of that list here or look for any error, especially this one: "failed to convert xxx to ISO_IR_192"
- also try to look at the response of the PACS especially the value of the tag [0008,0005] SpecificCharacterSet

What I think the issue might come from is that your PACS returns a specific character set that the underlying dicom library dues not support and therefore conversion fails (so for example: chinese ISO-IR 58 with escape sequences). This might also be configurable in your PACS.
Cheers
